version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    environment:
      - NODE_ENV=production
      - API_BASE_URL=${API_BASE_URL:-localhost:8000}
      - NEXT_PUBLIC_API_MOCKING=${NEXT_PUBLIC_API_MOCKING:-true}
      - CORS_ALLOWED_ORIGINS=http://localhost:9002,http://127.0.0.1:9002
    restart: unless-stopped
    networks:
      - sda-network

networks:
  sda-network:
    driver: bridge
